config/routes.rb
TrendTracker::Application.routes.draw do
  devise_for :users
  resources :trends, only: [:index, :create, :show, :destroy]
  root to: 'trends#index'

end

app/models/trend.rb
class Trend < ActiveRecord::Base
  belongs_to :user
  validates :query, presence: true
  geocoded_by :location

  after_validation :geocode

  def tweets
    # only want to load tweets once per page
    # this prevents us from searching every time this method is called for the
    # lifetime of the object
    if @tweets.nil?
      options = {}

      options[:geocode] = "#{latitude},#{longitude},50mi" if latitude && longitude
      options[:since_id] = last_tweet if last_tweet

      @tweets = Twitter.search(query, options)

      # set the last tweet so we know where to search from next time
      if @tweets.size > 0
        self.last_tweet = @tweets.first.id
        save
      end
    end

    @tweets
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :trends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :show, :destroy]
  before_filter :get_trends, only: [:index, :create, :show]

  def index
    if user_signed_in?
      @trend = @trends.first
    end
  end

  def create
    @trend = Trend.new(params[:trend].merge(user: current_user))

    @trend.save
    render :index
  end

  def show
    @trend = Trend.find(params[:id])

    render :index
  end

  def destroy
    @trend = Trend.find(params[:id])
    @trend.destroy

    redirect_to trends_path
  end

  private

  def get_trends
    @trends = current_user.trends.order("created_at DESC") if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TrendTracker"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") TrendTracker
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to "Log out", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Log in", new_user_session_path
                %li= link_to "Sign up", new_user_registration_path

    .container

      .content
        .row
          = yield
    
      %footer
        %p &copy; Jeff Smith
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"


app/views/trends/_form.html.haml
= form_for Trend.new, html: { class: 'form-inline' } do |f|
  = f.text_field :query, class: 'input-medium', placeholder: 'What'
  = f.text_field :location, class: 'input-medium', placeholder: 'Where'
  = f.submit :submit, class: 'btn btn-primary', value: 'add'

app/views/trends/_trend.html.haml
= link_to trend_path(trend) do
  %strong= trend.query
  - unless trend.location.blank?
    near #{trend.location}

app/views/trends/_tweet.html.haml
.row
  .span1
    %img{ :src => tweet.profile_image_url }
  .span6
    .row
      %strong= tweet.from_user
    .row
      = tweet.text

app/views/trends/index.html.haml
- if user_signed_in?
  .span5
    .well.sidebar-nav
      %h3 Your Trends
      %ul.nav.nav-list
        %li.nav-header
          New
        %li
          #notice= flash[:notice]
          #alert= flash[:alert]
          = render partial: 'form'
        - @trends.each do |trend|
          - if trend == @trend
            %li.active
              = render partial: 'trend', locals: { trend: trend }
          - else
            %li
              = render partial: 'trend', locals: { trend: trend }
  .span7
    - if @trend && @trend.valid?
      = link_to trend_path(@trend), method: :delete do
        %i.icon-remove
        Delete trend
      - if @trend.tweets.size > 0
        %ul#tweets.unstyled
          - @trend.tweets.each do |tweet|
            %li.tweet
              = render partial: 'tweet', locals: { tweet: tweet }
      - else
        %p No new tweets!
    - else
      %p Please enter a query or hashtag
- else
  Please
  = link_to "sign up", new_user_registration_path
  or
  = link_to "log in", new_user_session_path
  to continue.